/**
 * Course-home builder (Module S). Owner decision (2026-07-06): the student-site
 * VIEWS are the self-contained files themselves — a chapter is served as its
 * `.md.html` (slides as `.slides.html`, practice as its own `.md.html`, print
 * as `.paged.html`). Those files are generated by the caller (the worker);
 * this module builds only the **course home**, a navigation hub that links to
 * them (hub-and-spoke) — redesigned 2026-07-09 as the course's table of
 * contents: a hero (title + instructor/course number/department + intro), a
 * numbered module list per chapter (study guide always; slides/practice links
 * only when that chapter has authored one), and a placeholder section for the
 * not-yet-finalized "current term" space.
 *
 * Layout:
 *   index.html   — hero + module list + current-term placeholder
 *   build-info.json, .nojekyll
 *
 * The chapter/slides/practice/paged pages themselves (self-contained files)
 * are added to the file set by the caller after generation, each in the
 * educator's own theme choice **for that category** (study guide/practice can
 * use any orz-mdhtml theme; slides any orz-slides theme — not limited to two).
 * **Home chrome is its own identity (revised 2026-07-09), not a reused
 * orz-markdown theme:** content across categories can each be a different
 * orz theme, so there's no longer one specific theme for the home to visually
 * "belong to" — it now carries Alembic's own brand (copper accent, the same
 * tokens as the workspace app, `homeCss` below), with exactly one light and
 * one dark variant, auto-selected from the study guide's scheme (`theme`
 * param — light or dark, never a specific orz theme id). Copy-as-source and
 * math still come from the self-contained files' own runtime; the home itself
 * is `themedDocument` with a `css` override, so it still carries the orz
 * runtime script (copy-as-markdown) even though the visual theme is its own.
 *
 * `buildSite` (single-page callers) is untouched.
 */

import { md } from "orz-markdown";
import { rendererVersion } from "./index";
import { escapeHtml, themedDocument } from "./document";
import { learningResourceJsonLd, type LearningResourceMeta } from "./learning-resource";
import type { SiteFile } from "./site";
import type { RenderTheme } from "./theme-css";

export interface CourseChapter {
  /** URL-safe slug. */
  slug: string;
  title: string;
  /** Root-relative href of this chapter's self-contained reading page
   *  (e.g. "chapters/<slug>.md.html"); the caller generates the file. */
  viewHref: string;
  /** Optional per-chapter slide deck / practice questions / print view
   *  (self-contained files) — each chapter authors these independently, so a
   *  chapter with no deck/questions yet simply omits that link. */
  slidesHref?: string;
  practiceHref?: string;
  pagedHref?: string;
}

export interface CourseSiteInput {
  title: string;
  /** Short course intro shown on the home page (markdown). */
  description?: string;
  /** Course-identity line under the title — instructor / course number /
   *  department, each optional; present fields join with " · ", the line is
   *  omitted entirely when none are set. */
  instructor?: string;
  courseNumber?: string;
  department?: string;
  chapters: CourseChapter[];
  /** ISO timestamp, passed in for deterministic builds. */
  builtAt: string;
  /** LRMI/schema.org metadata; when present, emitted as JSON-LD on the index (M30). */
  meta?: LearningResourceMeta;
  /** Render theme — matches the educator's editor selection (default dark). */
  theme?: RenderTheme;
}

/**
 * Alembic's own home-page identity — light + dark, decoupled from every
 * orz-markdown/orz-slides built-in theme (content categories can each be a
 * *different* one of those; the home can't coherently "belong to" any single
 * one). Same tokens as the workspace app (`apps/web/src/app/globals.css` /
 * DESIGN.md): cool neutrals + one decoration color (copper), Source Serif 4
 * for display type over a system sans for body/UI — WCAG-verified pairs
 * (body ≥4.5:1, muted ≥4.5:1 too since it carries real metadata, not just
 * decoration). A full, self-sufficient stylesheet (base elements included)
 * since it no longer inherits `.markdown-body` styling from a vendored theme.
 */
function homeCss(theme: RenderTheme = "dark"): string {
  const dark = theme !== "light";
  const t = dark
    ? {
        canvas: "#0c0e16", surface: "#12151f", elevated: "#1a1e2c",
        edge: "#272b3d", edgeSoft: "#1c2030", ink: "#e6eaf3", muted: "#9aa3b8",
        accent: "#d99a6c", accentHover: "#e5ad84", accentInk: "#1c1108",
        accentSoft: "rgba(217,154,108,.16)",
      }
    : {
        canvas: "#fbfbfd", surface: "#ffffff", elevated: "#f3f4f8",
        edge: "#dee1ea", edgeSoft: "#eaecf2", ink: "#1b2030", muted: "#5a6276",
        accent: "#a4551e", accentHover: "#8a4a1c", accentInk: "#ffffff",
        accentSoft: "rgba(164,85,30,.10)",
      };
  return `@import url('https://fonts.googleapis.com/css2?family=Source+Serif+4:ital,opsz,wght@0,8..60,400;0,8..60,600;0,8..60,700;1,8..60,400&display=swap');
:root{
  --canvas:${t.canvas};--surface:${t.surface};--elevated:${t.elevated};
  --edge:${t.edge};--edge-soft:${t.edgeSoft};--ink:${t.ink};--muted:${t.muted};
  --accent:${t.accent};--accent-hover:${t.accentHover};--accent-ink:${t.accentInk};
  --accent-soft:${t.accentSoft};
  color-scheme:${theme};
}
*,*::before,*::after{box-sizing:border-box}
html{scroll-behavior:smooth}
body{
  margin:0;background:var(--canvas);color:var(--ink);
  font-family:system-ui,-apple-system,'Segoe UI',Roboto,sans-serif;
  line-height:1.65;padding:clamp(1.5rem,5vw,3.5rem) 1rem;
}
.markdown-body{
  max-width:52rem;margin:0 auto;background:var(--surface);
  border:1px solid var(--edge);border-radius:1rem;
  padding:clamp(1.75rem,6vw,3.25rem);
}
h1,h2,h3{font-family:'Source Serif 4',Georgia,serif;color:var(--ink);
  line-height:1.2;text-wrap:balance;margin:0 0 .5em}
h1{font-size:clamp(1.9rem,4.5vw,2.75rem);letter-spacing:-.01em;
  overflow-wrap:break-word;word-break:break-word;hyphens:auto}
h2{font-size:clamp(1.3rem,3vw,1.6rem);letter-spacing:-.005em}
p{margin:0 0 1em}
p:last-child{margin-bottom:0}
a{color:var(--accent);text-decoration:none}
a:hover{color:var(--accent-hover);text-decoration:underline}
strong,b{color:var(--ink);font-weight:600}
em,i{font-style:italic}
ul,ol{margin:0 0 1em;padding-left:1.4em}
li{margin-bottom:.3em}
blockquote{margin:1em 0;padding:.6em 1em;border-left:3px solid var(--accent-soft);
  background:var(--elevated);color:var(--muted);font-style:italic}
code{font-family:ui-monospace,'SF Mono',Menlo,monospace;font-size:.9em;
  background:var(--elevated);border:1px solid var(--edge-soft);border-radius:.3em;
  padding:.1em .4em}
hr{border:none;border-top:1px solid var(--edge);margin:1.5em 0}

.course-hero{margin-bottom:clamp(2rem,5vw,3.5rem)}
@media (max-width:480px){ .course-hero h1{font-size:1.6rem} }
.course-meta{margin:.4rem 0 0;font-size:.95rem;color:var(--muted);
  letter-spacing:.01em;text-align:left;hyphens:none}
.course-meta .sep{margin:0 .55em;opacity:.6}
.course-intro{margin-top:1.35rem;color:var(--ink);opacity:.92}

.modules{margin:clamp(2.5rem,6vw,4rem) 0;text-align:left}
.modules-head{display:flex;align-items:baseline;justify-content:space-between;
  gap:1rem .75rem;flex-wrap:wrap}
.modules-count{font-size:.8rem;color:var(--muted)}
.module-list{list-style:none;padding:0;margin:1.1rem 0 0}
.module-row{display:flex;gap:clamp(1rem,3vw,1.75rem);align-items:baseline;
  padding:1.15rem 0;border-bottom:1px solid var(--edge-soft)}
.module-row:first-child{border-top:1px solid var(--edge-soft)}
.module-num{flex:0 0 auto;min-width:1.7em;font-variant-numeric:tabular-nums;
  font-size:.95rem;font-weight:600;color:var(--accent)}
.module-main{flex:1;min-width:0;display:flex;flex-wrap:wrap;align-items:baseline;
  justify-content:space-between;gap:.4rem 1.5rem}
a.module-title{font-weight:600;font-size:1.05rem;color:var(--ink);text-decoration:none}
a.module-title:hover{color:var(--accent)}
.module-formats{display:flex;gap:1.1rem;flex-wrap:wrap;font-size:.82rem}
.module-formats a{text-decoration:none;color:var(--muted)}
.module-formats a:hover{color:var(--accent)}
.modules-empty{color:var(--muted);font-style:italic}

.current-term{margin:clamp(2.5rem,6vw,4rem) 0;padding:1.5rem 1.75rem;
  border:1px dashed var(--edge);border-radius:.75rem;text-align:left}
.current-term h2{margin-top:0}
.current-note{color:var(--muted);margin:0}

.site-footer{margin-top:3rem;padding-top:1rem;border-top:1px solid var(--edge-soft);
  font-size:.8rem;color:var(--muted);text-align:left}

@media (max-width:640px){
  .module-row{flex-direction:column;gap:.4rem}
  .module-num{min-width:0}
}
`;
}

/**
 * Build the course home + build metadata. The chapter/practice pages themselves
 * (self-contained `.md.html`) are added by the caller.
 */
export function buildCourseSite(input: CourseSiteInput): SiteFile[] {
  const files: SiteFile[] = [];
  const indexHead = input.meta ? learningResourceJsonLd(input.meta) : undefined;

  const metaParts = [input.instructor, input.courseNumber, input.department]
    .filter((s): s is string => Boolean(s && s.trim()))
    .map((s) => escapeHtml(s));
  const metaLine = metaParts.length
    ? `\n<p class="course-meta">${metaParts.join('<span class="sep">·</span>')}</p>`
    : "";
  const intro = input.description
    ? `\n<div class="course-intro">${md.render(input.description)}</div>`
    : "";
  const hero = `<header class="course-hero">\n<h1>${escapeHtml(input.title)}</h1>${metaLine}${intro}\n</header>`;

  const rows = input.chapters
    .map((c, i) => {
      const formats = [
        c.slidesHref ? `<a href="${escapeHtml(c.slidesHref)}">Slides</a>` : "",
        c.practiceHref ? `<a href="${escapeHtml(c.practiceHref)}">Practice questions</a>` : "",
        c.pagedHref ? `<a href="${escapeHtml(c.pagedHref)}">Print</a>` : "",
      ].filter(Boolean);
      const num = String(i + 1).padStart(2, "0");
      return `<li class="module-row">
<span class="module-num" aria-hidden="true">${num}</span>
<div class="module-main">
<a class="module-title" href="${escapeHtml(c.viewHref)}">${escapeHtml(c.title)}</a>
<span class="module-formats">${formats.join("")}</span>
</div>
</li>`;
    })
    .join("\n");
  const modulesBody = input.chapters.length
    ? `<ol class="module-list">\n${rows}\n</ol>`
    : `<p class="modules-empty">No modules published yet.</p>`;
  const count = input.chapters.length;
  const modules = `<section class="modules" aria-labelledby="modules-heading">
<div class="modules-head">
<h2 id="modules-heading">Modules</h2>${
    count ? `\n<span class="modules-count">${count} module${count === 1 ? "" : "s"}</span>` : ""
  }
</div>
${modulesBody}
</section>`;

  // Placeholder — the "current term" collection (announcements, due dates,
  // in-progress materials) isn't finalized yet; this just names the spot.
  const currentTerm = `<section class="current-term">
<h2>This term</h2>
<p class="current-note">Announcements and current-term materials will appear here once available.</p>
</section>`;

  const body = `${hero}\n${modules}\n${currentTerm}\n<footer class="site-footer">Published with Alembic</footer>`;

  files.push({
    path: "index.html",
    content: themedDocument({
      title: input.title,
      bodyHtml: body,
      headHtml: indexHead,
      theme: input.theme,
      css: homeCss(input.theme),
    }),
  });

  files.push({
    path: "build-info.json",
    content:
      JSON.stringify(
        { generator: "Alembic", renderer: rendererVersion(), builtAt: input.builtAt },
        null,
        2,
      ) + "\n",
  });
  // Tell GitHub Pages to serve files as-is (no Jekyll processing).
  files.push({ path: ".nojekyll", content: "" });

  return files;
}
