/**
 * Course-home builder (Module S). Owner decision (2026-07-06): the student-site
 * VIEWS are the self-contained files themselves — a chapter is served as its
 * `.md.html` (slides as `.slides.html`, print as `.paged.html`). Those files are
 * generated by the caller (the worker); this module builds only the **course
 * home**, a lightweight navigation hub that links to them (hub-and-spoke).
 *
 * Layout:
 *   index.html   — course title + intro + chapter cards (each links its
 *                  self-contained page) + optional practice list
 *   build-info.json, .nojekyll
 *
 * The chapter/practice pages (`chapters/<slug>.md.html`, `worksheets/<slug>.md.html`)
 * are added to the file set by the caller after generation. Copy-as-source,
 * themes, and math all come from the self-contained files' own runtime — and the
 * home itself is `themedDocument`, so it carries the orz runtime too.
 *
 * `buildSite` (single-page callers) is untouched.
 */

import { md } from "orz-markdown";
import { rendererVersion } from "./index";
import { escapeHtml, themedDocument } from "./document";
import { learningResourceJsonLd, type LearningResourceMeta } from "./learning-resource";
import type { SiteFile } from "./site";
import type { RenderTheme } from "./theme-css";

export interface CourseChapter {
  /** URL-safe slug. */
  slug: string;
  title: string;
  /** Root-relative href of this chapter's self-contained page
   *  (e.g. "chapters/<slug>.md.html"); the caller generates the file. */
  viewHref: string;
}

export interface CoursePractice {
  title: string;
  /** Root-relative href of the practice page (e.g. "worksheets/<slug>.md.html"). */
  viewHref: string;
}

export interface CourseSiteInput {
  title: string;
  /** Short course intro shown on the home page (markdown). */
  description?: string;
  chapters: CourseChapter[];
  practice?: CoursePractice[];
  /** ISO timestamp, passed in for deterministic builds. */
  builtAt: string;
  /** LRMI/schema.org metadata; when present, emitted as JSON-LD on the index (M30). */
  meta?: LearningResourceMeta;
  /** Render theme — matches the educator's editor selection (default dark). */
  theme?: RenderTheme;
}

/** Theme-neutral home chrome (greys via opacity, so it fits either orz theme). */
const SITE_STYLE = `<style>
.course-intro{opacity:.85}
.chapter-cards{list-style:none;padding:0;margin:1.5rem 0;display:grid;gap:.75rem}
.chapter-cards li{border:1px solid rgba(128,128,128,.28);border-radius:.6rem;padding:.85rem 1.1rem}
.chapter-cards .chapter-link{font-weight:600;text-decoration:none;font-size:1.1rem}
.site-footer{margin-top:3rem;padding-top:1rem;border-top:1px solid rgba(128,128,128,.2);font-size:.8rem;opacity:.6}
</style>`;

/** Combine the home style with any extra head HTML (e.g. JSON-LD). */
function head(extra?: string): string {
  return extra ? `${SITE_STYLE}\n${extra}` : SITE_STYLE;
}

/**
 * Build the course home + build metadata. The chapter/practice pages themselves
 * (self-contained `.md.html`) are added by the caller.
 */
export function buildCourseSite(input: CourseSiteInput): SiteFile[] {
  const files: SiteFile[] = [];
  const practice = input.practice ?? [];
  const indexHead = head(input.meta ? learningResourceJsonLd(input.meta) : undefined);
  const intro = input.description
    ? `<div class="course-intro">${md.render(input.description)}</div>`
    : "";

  const cards = input.chapters
    .map(
      (c) =>
        `<li><a class="chapter-link" href="${escapeHtml(c.viewHref)}">${escapeHtml(
          c.title,
        )}</a></li>`,
    )
    .join("\n");
  const chapterList = input.chapters.length
    ? `\n<ul class="chapter-cards">\n${cards}\n</ul>`
    : "";

  const practiceList = practice.length
    ? `\n<hr>\n<h2>Practice</h2>\n<ul>\n${practice
        .map((p) => `<li><a href="${escapeHtml(p.viewHref)}">${escapeHtml(p.title)}</a></li>`)
        .join("\n")}\n</ul>`
    : "";

  const body = `<h1>${escapeHtml(input.title)}</h1>${
    intro ? `\n${intro}` : ""
  }${chapterList}${practiceList}\n<footer class="site-footer">Published with Alembic</footer>`;

  files.push({
    path: "index.html",
    content: themedDocument({ title: input.title, bodyHtml: body, headHtml: indexHead, theme: input.theme }),
  });

  files.push({
    path: "build-info.json",
    content:
      JSON.stringify(
        { generator: "Alembic", renderer: rendererVersion(), builtAt: input.builtAt },
        null,
        2,
      ) + "\n",
  });
  // Tell GitHub Pages to serve files as-is (no Jekyll processing).
  files.push({ path: ".nojekyll", content: "" });

  return files;
}
