import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { serializeStudyGuide } from "@alembic/package-contract";
import {
  chapterPracticePath,
  chapterSlidesPath,
  listChapters,
  loadSlidesDeck,
  loadStudyGuide,
} from "@alembic/package-ops";
import {
  buildCourseSite,
  renderMarkdown,
  themeScheme,
  type CourseChapter,
  type CourseTermData,
  type CourseTermLink,
} from "@alembic/renderer";
import type { PackageRecord, PackageStore } from "@alembic/package-ops";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { SupabaseSandboxStore } from "@/lib/sandbox-store";
import { getRenderTheme } from "@/lib/theme";

export const dynamic = "force-dynamic";

/** Deterministic UTC date formatter for announcement stamps ("July 11, 2026"). */
const ANNOUNCEMENT_DATE_FMT = new Intl.DateTimeFormat("en-US", {
  timeZone: "UTC",
  year: "numeric",
  month: "long",
  day: "numeric",
});

function announcementDate(filename: string): string | undefined {
  const m = /^(\d{4})-(\d{2})-(\d{2})T/.exec(filename);
  if (!m) return undefined;
  const d = new Date(`${m[1]}-${m[2]}-${m[3]}T00:00:00Z`);
  return Number.isNaN(d.getTime()) ? undefined : ANNOUNCEMENT_DATE_FMT.format(d);
}

function splitAnnouncement(
  markdown: string,
  fallbackTitle: string,
): { title: string; body: string } {
  const lines = markdown.split("\n");
  let i = 0;
  while (i < lines.length && !lines[i].trim()) i++;
  const heading = /^#\s+(.+?)\s*$/.exec(lines[i]?.trim() ?? "");
  if (heading) {
    return { title: heading[1], body: lines.slice(i + 1).join("\n").trim() };
  }
  return { title: fallbackTitle, body: markdown.trim() };
}

function prettyFileTitle(filename: string): string {
  return filename.replace(/\.(md\.html|slides\.html|paged\.html|[^.]+)$/, "");
}

/**
 * Gather the CURRENT term's "This term" data for the preview — mirrors
 * `site-actions.ts`'s gathering (announcements parsed newest-first, assignments +
 * other materials as links). The preview only needs the shape, not the published
 * files, so it returns the data alone.
 */
async function previewCurrentTerm(
  store: PackageStore,
  packageId: string,
  record: PackageRecord,
): Promise<CourseTermData | undefined> {
  const termId = record.manifest.currentTerm;
  if (!termId) return undefined;
  const label = record.manifest.currentTermLabel?.trim() || termId;

  const sectionFiles = (await store.listFiles(packageId))
    .filter((f) => f.repo === "public")
    .map((f) => ({ file: f, seg: f.path.replace(/^\/+/, "").split("/") }))
    .filter(
      ({ seg }) => seg.length === 4 && seg[0] === "current" && seg[1] === termId,
    );

  const announcements = sectionFiles
    .filter(({ seg }) => seg[2] === "announcements" && seg[3].endsWith(".md"))
    .sort((a, b) => b.seg[3].localeCompare(a.seg[3]))
    .map(({ file, seg }) => {
      const { title, body } = splitAnnouncement(file.content, prettyFileTitle(seg[3]));
      return { title, date: announcementDate(seg[3]), bodyHtml: body ? renderMarkdown(body) : "" };
    });

  const linksFor = (section: string): CourseTermLink[] =>
    sectionFiles
      .filter(({ seg }) => seg[2] === section)
      .sort((a, b) => a.seg[3].localeCompare(b.seg[3]))
      .map(({ seg }) => ({
        title: prettyFileTitle(seg[3]),
        href: `current/${termId}/${section}/${seg[3]}`,
      }));

  return { label, announcements, assignments: linksFor("assignments"), misc: linksFor("misc") };
}

/**
 * Preview of the student-facing course HOME. The chapter/slides/practice pages
 * are the self-contained files, generated by the worker at publish — so the
 * preview shows the home hub and which links each chapter WILL have (mirroring
 * `site-actions.ts`'s per-chapter authored-content checks), not the pages
 * themselves.
 */
export default async function SitePreviewPage({
  params,
}: {
  params: Promise<{ packageId: string }>;
}) {
  const { packageId } = await params;
  const supabase = await createSupabaseServerClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect("/signin");

  const store = new SupabaseSandboxStore(supabase);
  const record = await store.getPackage(packageId);
  if (!record) notFound();

  const chapters: CourseChapter[] = [];
  for (const ch of await listChapters(store, packageId)) {
    const chapter: CourseChapter = { slug: ch.slug, title: ch.title, viewHref: `chapters/${ch.slug}.md.html` };

    const deck = await loadSlidesDeck(store, packageId, chapterSlidesPath(ch.slug));
    if (deck.source.trim()) chapter.slidesHref = `slides/${ch.slug}.slides.html`;

    const practiceDoc = await loadStudyGuide(store, packageId, chapterPracticePath(ch.slug));
    if (serializeStudyGuide(practiceDoc.preamble, practiceDoc.blocks).trim()) {
      chapter.practiceHref = `practice/${ch.slug}.md.html`;
    }

    chapters.push(chapter);
  }

  const currentTerm = await previewCurrentTerm(store, packageId, record);

  const cookie = await getRenderTheme();
  const orzTheme = record.manifest.theme ?? undefined;
  const files = buildCourseSite({
    title: record.title,
    description: record.manifest.description || undefined,
    instructor: record.manifest.courseContext?.instructor,
    courseNumber: record.manifest.courseContext?.courseNumber,
    department: record.manifest.courseContext?.department,
    chapters,
    currentTerm,
    license: record.manifest.license,
    builtAt: new Date().toISOString(),
    theme: orzTheme ? themeScheme(orzTheme) : cookie,
  });
  const indexHtml = files.find((f) => f.path === "index.html")?.content ?? "";

  return (
    <main className="mx-auto flex w-full max-w-4xl flex-1 flex-col gap-3 px-6 py-6">
      <div className="flex items-center justify-between">
        <Link href={`/workspace/${packageId}`} className="text-sm text-muted hover:text-ink">
          ← Back to editor
        </Link>
        <span className="text-xs text-faint">
          Course home preview — chapters open as self-contained pages once published
        </span>
      </div>
      <iframe
        title="Student page preview"
        srcDoc={indexHtml}
        className="h-[80vh] w-full rounded-xl border border-[var(--edge)] bg-[var(--bg)]"
      />
    </main>
  );
}
