import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { serializeStudyGuide } from "@alembic/package-contract";
import {
  chapterPracticePath,
  chapterSlidesPath,
  listChapters,
  loadSlidesDeck,
  loadStudyGuide,
} from "@alembic/package-ops";
import { buildCourseSite, themeScheme, type CourseChapter } from "@alembic/renderer";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { SupabaseSandboxStore } from "@/lib/sandbox-store";
import { getRenderTheme } from "@/lib/theme";

export const dynamic = "force-dynamic";

/**
 * Preview of the student-facing course HOME. The chapter/slides/practice pages
 * are the self-contained files, generated by the worker at publish — so the
 * preview shows the home hub and which links each chapter WILL have (mirroring
 * `site-actions.ts`'s per-chapter authored-content checks), not the pages
 * themselves.
 */
export default async function SitePreviewPage({
  params,
}: {
  params: Promise<{ packageId: string }>;
}) {
  const { packageId } = await params;
  const supabase = await createSupabaseServerClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect("/signin");

  const store = new SupabaseSandboxStore(supabase);
  const record = await store.getPackage(packageId);
  if (!record) notFound();

  const chapters: CourseChapter[] = [];
  for (const ch of await listChapters(store, packageId)) {
    const chapter: CourseChapter = { slug: ch.slug, title: ch.title, viewHref: `chapters/${ch.slug}.md.html` };

    const deck = await loadSlidesDeck(store, packageId, chapterSlidesPath(ch.slug));
    if (deck.source.trim()) chapter.slidesHref = `slides/${ch.slug}.slides.html`;

    const practiceDoc = await loadStudyGuide(store, packageId, chapterPracticePath(ch.slug));
    if (serializeStudyGuide(practiceDoc.preamble, practiceDoc.blocks).trim()) {
      chapter.practiceHref = `practice/${ch.slug}.md.html`;
    }

    chapters.push(chapter);
  }

  const cookie = await getRenderTheme();
  const orzTheme = record.manifest.theme ?? undefined;
  const files = buildCourseSite({
    title: record.title,
    description: record.manifest.description || undefined,
    instructor: record.manifest.courseContext?.instructor,
    courseNumber: record.manifest.courseContext?.courseNumber,
    department: record.manifest.courseContext?.department,
    chapters,
    builtAt: new Date().toISOString(),
    theme: orzTheme ? themeScheme(orzTheme) : cookie,
  });
  const indexHtml = files.find((f) => f.path === "index.html")?.content ?? "";

  return (
    <main className="mx-auto flex w-full max-w-4xl flex-1 flex-col gap-3 px-6 py-6">
      <div className="flex items-center justify-between">
        <Link href={`/workspace/${packageId}`} className="text-sm text-muted hover:text-ink">
          ← Back to editor
        </Link>
        <span className="text-xs text-faint">
          Course home preview — chapters open as self-contained pages once published
        </span>
      </div>
      <iframe
        title="Student page preview"
        srcDoc={indexHtml}
        className="h-[80vh] w-full rounded-xl border border-[var(--edge)] bg-[var(--bg)]"
      />
    </main>
  );
}
