import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { listArtifacts, listChapters } from "@alembic/package-ops";
import {
  buildCourseSite,
  type CourseChapter,
  type CoursePractice,
} from "@alembic/renderer";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { SupabaseSandboxStore } from "@/lib/sandbox-store";
import { slugForFile } from "@/lib/export";
import { getRenderTheme } from "@/lib/theme";

export const dynamic = "force-dynamic";

/**
 * Preview of the student-facing course HOME. The chapter/practice pages are the
 * self-contained `.md.html` files, generated by the worker at publish — so the
 * preview shows the home hub and its links; the pages themselves appear once
 * published.
 */
export default async function SitePreviewPage({
  params,
}: {
  params: Promise<{ packageId: string }>;
}) {
  const { packageId } = await params;
  const supabase = await createSupabaseServerClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect("/signin");

  const store = new SupabaseSandboxStore(supabase);
  const record = await store.getPackage(packageId);
  if (!record) notFound();

  const chapters: CourseChapter[] = (await listChapters(store, packageId)).map((ch) => ({
    slug: ch.slug,
    title: ch.title,
    viewHref: `chapters/${ch.slug}.md.html`,
  }));

  const practice: CoursePractice[] = (await listArtifacts(store, packageId)).map((a) => ({
    title: a.record.title,
    viewHref: `worksheets/${slugForFile(a.record.title)}-${a.record.artifactId.slice(4, 10)}.md.html`,
  }));

  const files = buildCourseSite({
    title: record.title,
    description: record.manifest.description || undefined,
    chapters,
    practice,
    builtAt: new Date().toISOString(),
    theme: await getRenderTheme(),
  });
  const indexHtml = files.find((f) => f.path === "index.html")?.content ?? "";

  return (
    <main className="mx-auto flex w-full max-w-4xl flex-1 flex-col gap-3 px-6 py-6">
      <div className="flex items-center justify-between">
        <Link href={`/workspace/${packageId}`} className="text-sm text-muted hover:text-ink">
          ← Back to editor
        </Link>
        <span className="text-xs text-faint">
          Course home preview — chapters open as self-contained pages once published
        </span>
      </div>
      <iframe
        title="Student page preview"
        srcDoc={indexHtml}
        className="h-[80vh] w-full rounded-xl border border-[var(--edge)] bg-[var(--bg)]"
      />
    </main>
  );
}
